"use strict";(self.webpackChunkdasarpemrogramanpython=self.webpackChunkdasarpemrogramanpython||[]).push([[5026],{3905:(a,e,n)=>{n.d(e,{Zo:()=>u,kt:()=>k});var t=n(7294);function r(a,e,n){return e in a?Object.defineProperty(a,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):a[e]=n,a}function i(a,e){var n=Object.keys(a);if(Object.getOwnPropertySymbols){var t=Object.getOwnPropertySymbols(a);e&&(t=t.filter((function(e){return Object.getOwnPropertyDescriptor(a,e).enumerable}))),n.push.apply(n,t)}return n}function o(a){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?i(Object(n),!0).forEach((function(e){r(a,e,n[e])})):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(n)):i(Object(n)).forEach((function(e){Object.defineProperty(a,e,Object.getOwnPropertyDescriptor(n,e))}))}return a}function l(a,e){if(null==a)return{};var n,t,r=function(a,e){if(null==a)return{};var n,t,r={},i=Object.keys(a);for(t=0;t<i.length;t++)n=i[t],e.indexOf(n)>=0||(r[n]=a[n]);return r}(a,e);if(Object.getOwnPropertySymbols){var i=Object.getOwnPropertySymbols(a);for(t=0;t<i.length;t++)n=i[t],e.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(a,n)&&(r[n]=a[n])}return r}var p=t.createContext({}),s=function(a){var e=t.useContext(p),n=e;return a&&(n="function"==typeof a?a(e):o(o({},e),a)),n},u=function(a){var e=s(a.components);return t.createElement(p.Provider,{value:e},a.children)},d="mdxType",c={inlineCode:"code",wrapper:function(a){var e=a.children;return t.createElement(t.Fragment,{},e)}},m=t.forwardRef((function(a,e){var n=a.components,r=a.mdxType,i=a.originalType,p=a.parentName,u=l(a,["components","mdxType","originalType","parentName"]),d=s(n),m=r,k=d["".concat(p,".").concat(m)]||d[m]||c[m]||i;return n?t.createElement(k,o(o({ref:e},u),{},{components:n})):t.createElement(k,o({ref:e},u))}));function k(a,e){var n=arguments,r=e&&e.mdxType;if("string"==typeof a||r){var i=n.length,o=new Array(i);o[0]=m;var l={};for(var p in e)hasOwnProperty.call(e,p)&&(l[p]=e[p]);l.originalType=a,l[d]="string"==typeof a?a:r,o[1]=l;for(var s=2;s<i;s++)o[s]=n[s];return t.createElement.apply(null,o)}return t.createElement.apply(null,n)}m.displayName="MDXCreateElement"},2719:(a,e,n)=>{n.r(e),n.d(e,{assets:()=>p,contentTitle:()=>o,default:()=>c,frontMatter:()=>i,metadata:()=>l,toc:()=>s});var t=n(7462),r=(n(7294),n(3905));const i={sidebar_position:46,title:"A.46. Python Error & Exception",sidebar_label:"A.46. Error & Exception"},o=void 0,l={unversionedId:"basic/error-exception",id:"basic/error-exception",title:"A.46. Python Error & Exception",description:"Secara teknsi Python interpreter mengenal dua jenis error, yaitu syntax error dan exception. Sebenarnya ada lagi satu jenis error lainnya, yaitu yang munculnya hanya di level linter (di editor) namun membuat eksekusi program menjadi gagal.",source:"@site/docs/basic/error-exception.md",sourceDirName:"basic",slug:"/basic/error-exception",permalink:"/basic/error-exception",draft:!1,tags:[],version:"current",sidebarPosition:46,frontMatter:{sidebar_position:46,title:"A.46. Python Error & Exception",sidebar_label:"A.46. Error & Exception"},sidebar:"tutorialSidebar",previous:{title:"A.45. Pattern Matching \u279c match",permalink:"/basic/pattern-matching"},next:{title:"A.47. Exception Handling \u279c try, except, else, finally",permalink:"/basic/exception-handling-try-except-else-finally"}},p={},s=[{value:"A.46.1. Syntax error",id:"a461-syntax-error",level:2},{value:"A.46.2. Exception",id:"a462-exception",level:2},{value:"A.46.3. Throw exception",id:"a463-throw-exception",level:2},{value:"A.46.4. Linter error / warning",id:"a464-linter-error--warning",level:2},{value:"Catatan chapter \ud83d\udcd1",id:"catatan-chapter-",level:2},{value:"\u25c9 Source code praktik",id:"-source-code-praktik",level:3},{value:"\u25c9 Chapter relevan lainnya",id:"-chapter-relevan-lainnya",level:3},{value:"\u25c9 Referensi",id:"-referensi",level:3}],u={toc:s},d="wrapper";function c(a){let{components:e,...i}=a;return(0,r.kt)(d,(0,t.Z)({},u,i,{components:e,mdxType:"MDXLayout"}),(0,r.kt)("p",null,"Secara teknsi Python interpreter mengenal dua jenis error, yaitu ",(0,r.kt)("em",{parentName:"p"},"syntax error")," dan ",(0,r.kt)("em",{parentName:"p"},"exception"),". Sebenarnya ada lagi satu jenis error lainnya, yaitu yang munculnya hanya di level linter (di editor) namun membuat eksekusi program menjadi gagal."),(0,r.kt)("p",null,"Pada chapter ini kita akan membahas tentang topik tersebut."),(0,r.kt)("h2",{id:"a461-syntax-error"},"A.46.1. Syntax error"),(0,r.kt)("p",null,"Syntax error adalah salah satu error jenis error yang ada di Python, yang jika muncul maka bisa dipastikan eksekusi program adalah gagal atau terhenti. Syntax error disebabkan oleh kesalah penulisan."),(0,r.kt)("p",null,"Misalnya ada typo pada pemanggilan fungsi print yang tidak sengaja tertulis sebagai ",(0,r.kt)("inlineCode",{parentName:"p"},"prind()"),", sedangkan di source code sendiri tidak ada fungsi lain yang dideklarasikan dengan nama itu, maka pada situasi seperti ini terjadi syntax error."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-python"},'prind("hello world")\n')),(0,r.kt)("p",null,"Output program:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"Python syntax error",src:n(6962).Z,width:"506",height:"158"})),(0,r.kt)("p",null,"Satu-satunya solusi untuk mengatasi syntax error adalah dengan memperbaiki kode, memastikan semua penulisannya benar sesuai aturan di Python."),(0,r.kt)("h2",{id:"a462-exception"},"A.46.2. Exception"),(0,r.kt)("p",null,"Exception adalah jenis error yang muncul saat ",(0,r.kt)("em",{parentName:"p"},"runtime")," (saat program dijalankan). Berbeda dengan syntax error yang munculnya saat proses eksekusi program (sebelum program benar-benar running)."),(0,r.kt)("p",null,"Salah satu exception yang umumnya ada di bahasa pemrograman adalah ",(0,r.kt)("strong",{parentName:"p"},"zero division error"),". Error ini muncul ketika ada operasi aritmatika pembagian suatu bilangan numerik terhadap bilangan ",(0,r.kt)("inlineCode",{parentName:"p"},"0"),"."),(0,r.kt)("p",null,"Contoh kasus exception:"),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-python"},'n1 = int(input("Enter the 1st number: "))\nn2 = int(input("Enter the 2nd number: "))\n\nres = n1 / n2\nprint(f"{n1} / {n2} = {res}")\n')),(0,r.kt)("p",null,"Output program:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"Python exception",src:n(8711).Z,width:"506",height:"271"})),(0,r.kt)("p",null,"Exception bisa diantisipasi dengan menambahkan validasi, misalnya untuk kasus di atas bisa dengan ditambahkan seleksi kondisi pengecekan nilai ",(0,r.kt)("inlineCode",{parentName:"p"},"n2"),". Jika nilainya adalah ",(0,r.kt)("inlineCode",{parentName:"p"},"0"),", maka program dihentikan dan pesan peringatan dimunculkan."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-python"},'n1 = int(input("Enter the 1st number: "))\nn2 = int(input("Enter the 2nd number: "))\n\nif n2 == 0:\n    print("we do not allow the value of 0 on the 2nd number")\nelse:\n    res = n1 / n2\n    print(f"{n1} / {n2} = {res}")\n')),(0,r.kt)("p",null,"Output program:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"Python exception",src:n(8546).Z,width:"417",height:"199"})),(0,r.kt)("p",null,"Alternatif solusi lainnya untuk mengatasi exception adalah dengan pengaplikasian kombinasi keyword ",(0,r.kt)("inlineCode",{parentName:"p"},"try")," dan ",(0,r.kt)("inlineCode",{parentName:"p"},"catch"),". Lebih detailnya akan dibahas di chapter berikutnya, di chapter ",(0,r.kt)("a",{parentName:"p",href:"#"},"Exception Handling (try, catch, finally)"),". "),(0,r.kt)("h2",{id:"a463-throw-exception"},"A.46.3. Throw exception"),(0,r.kt)("p",null,"Di atas kita belajar salah satu cara antisipasi exception, yaitu dengan penambahan validasi sesuai kebutuhan, jika kondisi berpotensi menghasilkan exception maka pesan custom error dimunculkan."),(0,r.kt)("p",null,"Selanjutnya, kita akan belajar cara untuk dengan sengaja membuat atau melempar exception (istilah umumnya ",(0,r.kt)("em",{parentName:"p"},"throwing exception"),"). Dengan melempar exception, program akan terhenti secara paksa."),(0,r.kt)("p",null,"Pada program berikut ini, sejumlah baris angka dimunculkan sesuai inputan. Jika inputannya ",(0,r.kt)("inlineCode",{parentName:"p"},"0")," atau bilangan negatif maka exception dilempar, membuat program terhenti."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-python"},'print("this program prints number from 0 to N")\nn = int(input("enter the value of N: "))\n\nif n <= 0:\n    raise Exception("we do not allow 0 or negative number")\n\nfor d in range(0, n):\n    print(d + 1)\n')),(0,r.kt)("p",null,"Outputnya:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"Python exception",src:n(4114).Z,width:"506",height:"304"})),(0,r.kt)("p",null,"Cara membuat exception adalah dengan menggunakan keyword ",(0,r.kt)("inlineCode",{parentName:"p"},"raise")," diikuti dengan pemanggilan class ",(0,r.kt)("inlineCode",{parentName:"p"},"Exception()")," yang argument-nya diisi dengan custom error."),(0,r.kt)("p",null,"Pada contoh di atas, exception dimunculkan dengan pesan error ",(0,r.kt)("inlineCode",{parentName:"p"},"we do not allow 0 or negative number"),". "),(0,r.kt)("h2",{id:"a464-linter-error--warning"},"A.46.4. Linter error / warning"),(0,r.kt)("p",null,"Linter adalah suatu program utilisa yang berguna untuk melakukan pengecekan kualitas kode saat pengembangan (penulisan kode). Linter akan memunculkan error atau warning jika ditemukan pada beberapa bagian kode yang ditulis adalah kurang baik."),(0,r.kt)("p",null,"Di Python, jika pembaca menggunakan VSCode editor dan sudah meng-install extension Python, linter akan otomatis bekerja saat menulis kode."),(0,r.kt)("p",null,"Linter error adalah warning yang muncul di editor saat kode tidak sesuai baik secara ",(0,r.kt)("em",{parentName:"p"},"syntactic")," maupun secara ",(0,r.kt)("em",{parentName:"p"},"semantic"),". Error yang muncul karena alasan semantik tidak akan membuat program terhenti atau gagal running. Program tetap bisa jalan normal saat di-run."),(0,r.kt)("p",null,"Salah satu contoh linter error adalah ketika ada suatu fungsi yang saat pemanggilannya diisi oleh tipe data dengan tipe yang tidak sesuai dibading dengan yang sudah dideklarasikan. Pada situasi seperti ini error muncul di editor, ada highlight merah di situ."),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"Python exception",src:n(8616).Z,width:"831",height:"260"})),(0,r.kt)("p",null,"Meskipun tidak membuat program terhenti saat running, ada baiknya untuk selalu menulis kode dengan baik dan benar sesuai aturan."),(0,r.kt)("hr",null),(0,r.kt)("div",{class:"section-footnote"},(0,r.kt)("h2",{id:"catatan-chapter-"},"Catatan chapter \ud83d\udcd1"),(0,r.kt)("h3",{id:"-source-code-praktik"},"\u25c9 Source code praktik"),(0,r.kt)("pre",null,(0,r.kt)("a",{href:"https://github.com/novalagung/dasarpemrogramanpython-example/tree/master/error-exception"},"github.com/novalagung/dasarpemrogramanpython-example/../error-exception")),(0,r.kt)("h3",{id:"-chapter-relevan-lainnya"},"\u25c9 Chapter relevan lainnya"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("a",{parentName:"li",href:"/basic/exception-handling-try-except-else-finally"},"Exception Handling \u279c try, except, else, finally"))),(0,r.kt)("h3",{id:"-referensi"},"\u25c9 Referensi"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("a",{parentName:"li",href:"https://docs.python.org/3/tutorial/errors.html"},"https://docs.python.org/3/tutorial/errors.html")))))}c.isMDXComponent=!0},6962:(a,e,n)=>{n.d(e,{Z:()=>t});const t=n.p+"assets/images/error-exception-1-5c12d06876bc8f9dc14a413e097dd713.png"},8711:(a,e,n)=>{n.d(e,{Z:()=>t});const t=n.p+"assets/images/error-exception-2-c7a96f6c27a36d19f33de6e75b24457b.png"},8546:(a,e,n)=>{n.d(e,{Z:()=>t});const t=n.p+"assets/images/error-exception-3-25c29f9288b84e5e07a59654f1797fc6.png"},4114:(a,e,n)=>{n.d(e,{Z:()=>t});const t=n.p+"assets/images/error-exception-4-0d0d61e6c0942475ea792282d1163a87.png"},8616:(a,e,n)=>{n.d(e,{Z:()=>t});const t=n.p+"assets/images/error-exception-5-a3ca963f75be921472e29deaeba03c23.png"}}]);